apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: test1-index.html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-test-configmap
          items:
          - key: test1-index.html
            path: test1-index.html
