apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s-load-balancing-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-test-service
            port:
              number: 80
      - path: /test1
        pathType: Prefix
        backend:
          service:
            name: nginx-test1-service
            port:
              number: 80
      - path: /test2
        pathType: Prefix
        backend:
          service:
            name: nginx-test2-service
            port:
              number: 80
