apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test1-service
spec:
  selector:
    app: nginx
    version: test1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test2-service
spec:
  selector:
    app: nginx
    version: test2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
